services:
  - type: web
    name: maineblanc-project
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn maineblanc_project.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: RENDER
        value: "True"
      - key: SECRET_KEY
        generateValue: true
      - key: EMAIL_FROM_CLIENT
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: SITE_URL
        value: "https://maineblanc-project.onrender.com"
